[doc] Improve compatibility matrix notes
kubernetes/kube-state-metrics pull request #1512
Opened 2021-06-24 14:42 UTC by stevehipwell

**What this PR does / why we need it**:
This PR tidies up the notes on the compatibility matrix to better explain how to use kube-state-metrics on K8s v1.17 & v1.18.

**Which issue(s) this PR fixes**:
Fixes #1507.

2021-06-24 14:42 UTC, stevehipwell commented
@lilic as requested.

2021-06-24 14:42 UTC, stevehipwell commented
/assign @lilic

2021-06-29 11:15 UTC, mrueg commented on README.md
> +**Note:** kube-state-metrics releases from `v2.0.0` work on Kubernetes v1.17 and v1.18 but the Ingress and CertificateSigningRequest resource metrics are missing. If you require those metrics and are
```suggestion
**Note:** kube-state-metrics releases from `v2.0.0` work on Kubernetes v1.17 and v1.18 but the Ingress and CertificateSigningRequest resource metrics are not available. If you require those metrics and are on an older Kubernetes version you can use the `v1.9.8` kube-state-metrics release; but please be aware that due to CLI flag changes this image is not compatible with `v2.0.0` and later.
```

2021-07-05 22:53 UTC, spaparaju requested changes

2021-07-05 22:53 UTC, spaparaju commented on README.md
> +**Note:** kube-state-metrics releases from `v2.0.0` work on Kubernetes v1.17 and v1.18 but the Ingress and CertificateSigningRequest resource metrics are not available. If you require those metrics a
The current `kube-state-metrics v2.0.0 +` releases work on Kubernetes v1.17 and v1.18 excluding Ingress or CertificateSigningRequest resource metrics. If you require those metrics on an older Kubernetes version, use `kube-state-metrics v1.9.8` .

2021-07-05 22:53 UTC, spaparaju commented on README.md
> +The official [Helm chart](https://artifacthub.io/packages/helm/prometheus-community/kube-state-metrics/) is maintained in [prometheus-community/helm-charts](https://github.com/prometheus-community/he
Starting from `kube-state-metrics v2.13.3`, the official Helm chart is maintained at [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics).

2021-07-06 08:37 UTC, stevehipwell commented
@spaparaju I've added your changes whilst still keeping one of the important points that I was trying to make around the image compatibility of the Helm chart due to the CLI args changing. This matters where the kube-state-metrics chart is included from another chart (e.g. kube-prometheus-stack) where we can only override the values such as image tag and not the chart version.

2021-07-06 17:57 UTC, spaparaju approved these changes
LGTM 👍

2021-07-13 15:10 UTC, lilic reviewed
/lgtm

Thanks!

2021-07-13 15:14 UTC, merged