fix: de-duplication of custom resource metrics
kubernetes/kube-state-metrics pull request #2502
Opened 2024-09-18 23:39 UTC by bartlettc22

**What this PR does / why we need it**:
Fixes an issue that causes custom resource metrics to duplicate every time a CR resource that KSM is watching changed.  The duplication was happening because the informer events (add/delete) triggered a subsequent call to `WithEnabledResources` in `store.Builder`.  This would append, but not de-duplicate the CR resources to the `enabledResources` list. This, in turn, would cause the custom resources to be be added multiple times when the store was built.

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
Does not change cardinality

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2066

2024-09-19 16:43 UTC, dgrisonnet commented
/assign @rexagod 
/triage accepted

2024-09-22 11:10 UTC, rexagod requested changes
Requested a minor change below. Thank you for the much needed patch!

2024-10-01 19:38 UTC, bartlettc22 commented
> Requested a minor change below. Thank you for the much needed patch!

Updated - thanks for the suggestion!

2024-10-08 08:01 UTC, mrueg commented
/lgtm

/hold 
for others to review

2024-10-08 08:03 UTC, mrueg commented on internal/store/builder_test.go
> +				t.Fatal("Test error for Desc: %s. Got Error: %v", test.Desc, err)
```suggestion
				t.Fatalf("Test error for Desc: %s. Got Error: %v", test.Desc, err)
```

2024-10-15 08:17 UTC, mrueg commented
/hold cancel
/lgtm

2024-10-15 08:18 UTC, merged